// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCumrdmZM65cnW-4GRJDYvWi51c5KcpLqU',
    appId: '1:220826943292:web:bf5ff4cebf12629d5ca839',
    messagingSenderId: '220826943292',
    projectId: 'mosaic-221f8',
    authDomain: 'mosaic-221f8.firebaseapp.com',
    storageBucket: 'mosaic-221f8.firebasestorage.app',
    measurementId: 'G-Y7LK1RQGH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQNhUBowQZZfNUwRX-KnKqClYwZEYnOyQ',
    appId: '1:220826943292:android:96828c42dea4a1495ca839',
    messagingSenderId: '220826943292',
    projectId: 'mosaic-221f8',
    storageBucket: 'mosaic-221f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFW-Tjn7N9PnkrjumwV57wXQ65g5yWiX0',
    appId: '1:220826943292:ios:5df08d615f3ad8535ca839',
    messagingSenderId: '220826943292',
    projectId: 'mosaic-221f8',
    storageBucket: 'mosaic-221f8.firebasestorage.app',
    androidClientId: '220826943292-dr7c2biiuqca3ecv8f88uc0f4ln2hpg0.apps.googleusercontent.com',
    iosClientId: '220826943292-6bg9i02qh76kh33n95rp6o6ncbh3ie7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mosaic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFW-Tjn7N9PnkrjumwV57wXQ65g5yWiX0',
    appId: '1:220826943292:ios:5df08d615f3ad8535ca839',
    messagingSenderId: '220826943292',
    projectId: 'mosaic-221f8',
    storageBucket: 'mosaic-221f8.firebasestorage.app',
    androidClientId: '220826943292-dr7c2biiuqca3ecv8f88uc0f4ln2hpg0.apps.googleusercontent.com',
    iosClientId: '220826943292-6bg9i02qh76kh33n95rp6o6ncbh3ie7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mosaic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCumrdmZM65cnW-4GRJDYvWi51c5KcpLqU',
    appId: '1:220826943292:web:a6123cad32e8524c5ca839',
    messagingSenderId: '220826943292',
    projectId: 'mosaic-221f8',
    authDomain: 'mosaic-221f8.firebaseapp.com',
    storageBucket: 'mosaic-221f8.firebasestorage.app',
    measurementId: 'G-7H5MDV8BB6',
  );
}
